services:
  - type: web
    name: audio-typewriter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    disk:
      name: video-storage
      mountPath: /opt/render/project/src/output_videos
      sizeGB: 10 